radius_threshold = 0.05;
angle_threshold = 0.05;
use_probability = true;
rematch = true;
sample_values = vals_mkIV;
gcp_path = gcp_path_lerkendal;
orthophoto = lerkendal;
dsm = dem;

tic;
[CM_horn, ST_horn, RMSE_horn, mirrored_horn] = main(...
    orthophoto, ...
    gcp_path, ...
    'DEM', dsm, ...
    'GCPSample', sample_values, ...
    'UseProbability', use_probability, ...
    'RadiusThreshold', radius_threshold, ...
    'AngleThreshold', angle_threshold, ...
    'Rematch', rematch, ...
    'OrientationAlgorithm', 'Horn');
toc;

tic;
[CM_horn_hilden, ST_horn_hilden, RMSE_horn_hilden, mirrored_horn_hilden] = main(...
    orthophoto, ...
    gcp_path, ...
    'DEM', dsm, ...
    'GCPSample', sample_values, ...
    'UseProbability', use_probability, ...
    'RadiusThreshold', radius_threshold, ...
    'AngleThreshold', angle_threshold, ...
    'Rematch', rematch, ...
    'OrientationAlgorithm', 'HornHilden');
toc;
tic;
[CM_umeyama, ST_umeyama, RMSE_umeyama, mirrored_umeyama] = main(...
    orthophoto, ...
    gcp_path, ...
    'DEM', dsm, ...
    'GCPSample', sample_values, ...
    'UseProbability', use_probability, ...
    'RadiusThreshold', radius_threshold, ...
    'AngleThreshold', angle_threshold, ...
    'Rematch', rematch, ...
    'OrientationAlgorithm', 'ShinjiUmeyama');
toc;
